spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

rsa:
  key:
    public:
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhkzU2adLEQjMbyIgcwDYRRiUPiW+Hn0pavQukDB2zh083Qlpfwk/J2jwbjEekbX6XR
      JlWkSkSt7VocJ9ishtSu8iPuzVBQ6lSQ/HqiQcUzY3dHpWgwFiYlML+PutyGomTRUFeYYY/4neTJbMEWZixhLveZ9jszhLwg9LD9kW67GtUTOq
      zErn8wXrT0YoOzBBvnW21pYoUwQ+lL2+z0Iu8dcBRVlEkUoUqwy06fzbjWuv/7vMrPCWnTyuNn2S5sx2Cm35YJzUnLbA0jLT88KhueyX7wv1pS
      fY9WAUk6ntpYh+qurTrdQhwiPKb4cQlncrolw+zoRqWJccNcX9/jxiZwIDAQAB
    private:
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCGTNTZp0sRCMxvIiBzANhFGJQ+Jb4efSlq9C6QMHbOHTzdCWl/CT8naPBuMR
      6RtfpdEmVaRKRK3tWhwn2KyG1K7yI+7NUFDqVJD8eqJBxTNjd0elaDAWJiUwv4+63IaiZNFQV5hhj/id5MlswRZmLGEu95n2OzOEvCD0sP2Rbr
      sa1RM6rMSufzBetPRig7MEG+dbbWlihTBD6Uvb7PQi7x1wFFWUSRShSrDLTp/NuNa6//u8ys8JadPK42fZLmzHYKbflgnNSctsDSMtPzwqG57J
      fvC/WlJ9j1YBSTqe2liH6q6tOt1CHCI8pvhxCWdyuiXD7OhGpYlxw1xf3+PGJnAgMBAAECggEALJuId2LhxB6wCJnFPW2iaBDp7FqM84OPJj9E
      2A/A5mU/ugtORyvDFkv80BzwkmVna1KY54q1J0ksnDYFjPtVkfYr4cq4Vp2uuL3NC+5CmkD/2mhoI8tp6k67Q1AVQORBJIk+8EZiNz6L39SWo5
      DmbfQMJtGSRA0G3MZHoFPzEQXKMHnleGDVETjjwp27yXH110na/Pu14mrxVarQ9+rWoTNMJLX5ahqdRhs8iWA3A3U6TvQtTRXNw7nhI3GBnrqr
      4LXtuIbMuLr94owVPnzxZmoQmkLKhfza1QpcYvg3SBQFDCmc3lc+onvN6TJEgiVK7vo4qaBEk4JAbVBiWoLygQKBgQD7IZ9E41wuyjzaqbxMNm
      3Yr/sN5cnJVJFkrWHenpwiFF5Bj8IwqZef0A3PoloFMNIC1doVuQmteN7QrBuhgyJi3gc+qXXBCQUAIF28VZgFPWD0gk/YyviX4OBv/RhuFXje
      f/78sji164QAhcSAY3Kd7JwMY2PTRQc8WMWxguyVPwKBgQCI516zaFdHk7ATDTNSYn4dThU2LEYsxo22/ePXgJMQBDYTQUdRPw2JQ1PqZnB/ku
      4wdFG3sMjFR0aR1c5cc/v9lrGjTpK9ZwIdrXs+0fsBri45t/YbDjhGy/5bJAPgdv8Buso9cJka0AJ6KnyvwmESUR2IFTfxoky/OLj82nYg2QKB
      gANbU7GsCFNnyKBznFy4bYdz8rsg0y2pv7fEyYYcQKID+66MqV/VJH2yXjzkQqfHG0eGbD/WFVcIQpIver8R7ae8qAQiZ7yIzlROGnKmAj4vr9
      gU1dRkAialjtpwW589EjyHIXVnPHLSDxWitBmzOpj5zKwtt+vfBFW+KgZRZbApAoGAQZY+q0qwjaz2bJolXTGsY5O128coM2lIGUPW9LY3PjQW
      R/E9HnJLpNfpiuFawfN9Qx9mys7Z0JFOAK3ieC5kqd+Y6LjK2gxQWjFzWuw0CWEN6j70m4+bbGdsSvOdG9tGXejD3N1lrA+9MBPMulMwOBs+P6
      SSsaNkizO8g/6RGzkCgYASycUIT1QOI3R6VFKyizcuKYyfIy9o4g82/eQ7xsxS7aWGIW7N7nF7kNgV0FMgMHupZFKnVtqctiCuzpFQRfcH7ceb
      kaQ434CQb7SbgJooblKBRQpmvk4hF4K3U9IjIXMm+4zypEylPK/4IgREJd64j1oizYUW8yrexanY5wfPEQ==
